### ISSUE TITLE
Support metadata extraction and filter for more accurate query

### ISSUE THREAD

**Issue by Mini256** [pingcap/tidb.ai#121]
## Tasks

- [x] https://github.com/pingcap/tidb.ai/pull/98
- [x] [Support metadata extraction from HTML label](https://github.com/pingcap/tidb.ai/pull/123)
- [x] Add post filters to filter the ANN search result by metadata https://github.com/pingcap/tidb.ai/pull/122
- [ ] Add config page for the metadata extraction rule
- [ ] Experiment: Embedding text combined with the metadata extracted by document
