### ISSUE TITLE
milestone 1: eating our own dog food

### ISSUE THREAD

**Issue by sykp241095** [pingcap/tidb.ai#2]
## Background
As we develop Vector Search in TiDB Serverless, we'll build an app to test how easy it is to use. This app will provide answers to TiDB usage questions on our official websites using our in-progress vector storage in TiDB Serverless.

## Todo list
* [x] core rag logic
  * [x] data source management
    * [x] upload pdf/markdown/csv etc.
    * [x] crawl sitemap.xml of a domain
  * [x] ui/ux
    * [x] conversational search
      * [x] chat history mgmt after login
    * [x] embeddable js
* [x] system settings
  * [x] overview: statistics of chats & docs
  * [x] basic info settings
    * [x] logo
    * [x] site name
    * [x] search title & subtitle
    * [x] example questions, max to 4
    * [x] footer links
    * [x] GitHub / Discord etc. social media links top-right
  * [x] oauth configurations
    * [x] GitHub
    * [x] Gmail
  * [x] (pre|post| prompt settings
  * [x] rag loader & spliter configruations: chunk size, overlap etc.
* [x] Use llamaindex-ts as RAG engine
* [ ] add widget on the bottom-right of (www|ask).pingcap.com to answer questions about tidb usage / use cases
