### ISSUE TITLE
[draft] milestone 2:  private beta

### ISSUE THREAD

**Issue by sykp241095** [pingcap/tidb.ai#5]
## Background
For our next milestone, we'll focus on making our app easier to deploy and use:

Product Refinement:
* Dedicate efforts to polishing the product, ensuring it meets user expectations in usability.

Deployment:
* Add support for deploying on Vercel(maybe and Cloudflare).
* Make it possible to deploy locally using tools like npx for quick testing.

Content Updates:
* Create a welcoming landing page for new visitors.
* Write usage docs/api docs to help users get started and integrate.

## Todo list
* [ ] #80 
* [ ] product
  * [ ] api & api token mgmt
  * [ ] more  LLM support(maybe need to re-split/re-index/re-embedding the content of docs)
  * [ ] support more data source: word etc.
  * [ ] Role-based access control & mgmt(user, admin)
* [ ] deployment
  * [ ] manually deployment(with npx etc.)
  * [ ] docker
  * [ ] Vercel
  * [ ] Cloudflare(optional)
  * [ ] fly.io(optional)
  * [ ] LLM/tokens usage statistic
 * [ ] security
   * [ ] cross-domain white list
* [ ] content
  * [ ] landing page
    * [ ] /
    * [ ] /showcases
    * [ ] /docs/get-started
    * [ ] /docs/api
  * [ ] README.md
